#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace model
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="sistemaJogos")]
	public partial class conexaoBancoDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insertjogo(jogo instance);
    partial void Updatejogo(jogo instance);
    partial void Deletejogo(jogo instance);
    partial void Insertcliente(cliente instance);
    partial void Updatecliente(cliente instance);
    partial void Deletecliente(cliente instance);
    partial void Insertcompra(compra instance);
    partial void Updatecompra(compra instance);
    partial void Deletecompra(compra instance);
    #endregion
		
		public conexaoBancoDataContext() : 
				base(global::model.Properties.Settings.Default.sistemaJogosConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public conexaoBancoDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public conexaoBancoDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public conexaoBancoDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public conexaoBancoDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<jogo> jogos
		{
			get
			{
				return this.GetTable<jogo>();
			}
		}
		
		public System.Data.Linq.Table<cliente> clientes
		{
			get
			{
				return this.GetTable<cliente>();
			}
		}
		
		public System.Data.Linq.Table<compra> compras
		{
			get
			{
				return this.GetTable<compra>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.jogos")]
	public partial class jogo : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idjogos;
		
		private string _nome;
		
		private string _descricao;
		
		private string _img;
		
		private System.Nullable<System.DateTime> _dtLancamentos;
		
		private string _plataforma;
		
		private System.Nullable<float> _preco;
		
		private System.Nullable<bool> _validacao;
		
		private System.Nullable<int> _quantidade;
		
		private EntitySet<compra> _compras;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidjogosChanging(int value);
    partial void OnidjogosChanged();
    partial void OnnomeChanging(string value);
    partial void OnnomeChanged();
    partial void OndescricaoChanging(string value);
    partial void OndescricaoChanged();
    partial void OnimgChanging(string value);
    partial void OnimgChanged();
    partial void OndtLancamentosChanging(System.Nullable<System.DateTime> value);
    partial void OndtLancamentosChanged();
    partial void OnplataformaChanging(string value);
    partial void OnplataformaChanged();
    partial void OnprecoChanging(System.Nullable<float> value);
    partial void OnprecoChanged();
    partial void OnvalidacaoChanging(System.Nullable<bool> value);
    partial void OnvalidacaoChanged();
    partial void OnquantidadeChanging(System.Nullable<int> value);
    partial void OnquantidadeChanged();
    #endregion
		
		public jogo()
		{
			this._compras = new EntitySet<compra>(new Action<compra>(this.attach_compras), new Action<compra>(this.detach_compras));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idjogos", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int idjogos
		{
			get
			{
				return this._idjogos;
			}
			set
			{
				if ((this._idjogos != value))
				{
					this.OnidjogosChanging(value);
					this.SendPropertyChanging();
					this._idjogos = value;
					this.SendPropertyChanged("idjogos");
					this.OnidjogosChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nome", DbType="VarChar(255)")]
		public string nome
		{
			get
			{
				return this._nome;
			}
			set
			{
				if ((this._nome != value))
				{
					this.OnnomeChanging(value);
					this.SendPropertyChanging();
					this._nome = value;
					this.SendPropertyChanged("nome");
					this.OnnomeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_descricao", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string descricao
		{
			get
			{
				return this._descricao;
			}
			set
			{
				if ((this._descricao != value))
				{
					this.OndescricaoChanging(value);
					this.SendPropertyChanging();
					this._descricao = value;
					this.SendPropertyChanged("descricao");
					this.OndescricaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_img", DbType="VarChar(1000)")]
		public string img
		{
			get
			{
				return this._img;
			}
			set
			{
				if ((this._img != value))
				{
					this.OnimgChanging(value);
					this.SendPropertyChanging();
					this._img = value;
					this.SendPropertyChanged("img");
					this.OnimgChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dtLancamentos", DbType="Date")]
		public System.Nullable<System.DateTime> dtLancamentos
		{
			get
			{
				return this._dtLancamentos;
			}
			set
			{
				if ((this._dtLancamentos != value))
				{
					this.OndtLancamentosChanging(value);
					this.SendPropertyChanging();
					this._dtLancamentos = value;
					this.SendPropertyChanged("dtLancamentos");
					this.OndtLancamentosChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_plataforma", DbType="VarChar(50)")]
		public string plataforma
		{
			get
			{
				return this._plataforma;
			}
			set
			{
				if ((this._plataforma != value))
				{
					this.OnplataformaChanging(value);
					this.SendPropertyChanging();
					this._plataforma = value;
					this.SendPropertyChanged("plataforma");
					this.OnplataformaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_preco", DbType="Real")]
		public System.Nullable<float> preco
		{
			get
			{
				return this._preco;
			}
			set
			{
				if ((this._preco != value))
				{
					this.OnprecoChanging(value);
					this.SendPropertyChanging();
					this._preco = value;
					this.SendPropertyChanged("preco");
					this.OnprecoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_validacao", DbType="Bit")]
		public System.Nullable<bool> validacao
		{
			get
			{
				return this._validacao;
			}
			set
			{
				if ((this._validacao != value))
				{
					this.OnvalidacaoChanging(value);
					this.SendPropertyChanging();
					this._validacao = value;
					this.SendPropertyChanged("validacao");
					this.OnvalidacaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_quantidade", DbType="Int")]
		public System.Nullable<int> quantidade
		{
			get
			{
				return this._quantidade;
			}
			set
			{
				if ((this._quantidade != value))
				{
					this.OnquantidadeChanging(value);
					this.SendPropertyChanging();
					this._quantidade = value;
					this.SendPropertyChanged("quantidade");
					this.OnquantidadeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="jogo_compra", Storage="_compras", ThisKey="idjogos", OtherKey="jogos_idjogos")]
		public EntitySet<compra> compras
		{
			get
			{
				return this._compras;
			}
			set
			{
				this._compras.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_compras(compra entity)
		{
			this.SendPropertyChanging();
			entity.jogo = this;
		}
		
		private void detach_compras(compra entity)
		{
			this.SendPropertyChanging();
			entity.jogo = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.clientes")]
	public partial class cliente : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idclientes;
		
		private string _nome;
		
		private System.DateTime _dtNascimento;
		
		private System.Nullable<long> _cpf;
		
		private float _valorGasto;
		
		private EntitySet<compra> _compras;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidclientesChanging(int value);
    partial void OnidclientesChanged();
    partial void OnnomeChanging(string value);
    partial void OnnomeChanged();
    partial void OndtNascimentoChanging(System.DateTime value);
    partial void OndtNascimentoChanged();
    partial void OncpfChanging(System.Nullable<long> value);
    partial void OncpfChanged();
    partial void OnvalorGastoChanging(float value);
    partial void OnvalorGastoChanged();
    #endregion
		
		public cliente()
		{
			this._compras = new EntitySet<compra>(new Action<compra>(this.attach_compras), new Action<compra>(this.detach_compras));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idclientes", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int idclientes
		{
			get
			{
				return this._idclientes;
			}
			set
			{
				if ((this._idclientes != value))
				{
					this.OnidclientesChanging(value);
					this.SendPropertyChanging();
					this._idclientes = value;
					this.SendPropertyChanged("idclientes");
					this.OnidclientesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nome", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string nome
		{
			get
			{
				return this._nome;
			}
			set
			{
				if ((this._nome != value))
				{
					this.OnnomeChanging(value);
					this.SendPropertyChanging();
					this._nome = value;
					this.SendPropertyChanged("nome");
					this.OnnomeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dtNascimento", DbType="DateTime NOT NULL")]
		public System.DateTime dtNascimento
		{
			get
			{
				return this._dtNascimento;
			}
			set
			{
				if ((this._dtNascimento != value))
				{
					this.OndtNascimentoChanging(value);
					this.SendPropertyChanging();
					this._dtNascimento = value;
					this.SendPropertyChanged("dtNascimento");
					this.OndtNascimentoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cpf", DbType="BigInt")]
		public System.Nullable<long> cpf
		{
			get
			{
				return this._cpf;
			}
			set
			{
				if ((this._cpf != value))
				{
					this.OncpfChanging(value);
					this.SendPropertyChanging();
					this._cpf = value;
					this.SendPropertyChanged("cpf");
					this.OncpfChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_valorGasto", DbType="Real NOT NULL")]
		public float valorGasto
		{
			get
			{
				return this._valorGasto;
			}
			set
			{
				if ((this._valorGasto != value))
				{
					this.OnvalorGastoChanging(value);
					this.SendPropertyChanging();
					this._valorGasto = value;
					this.SendPropertyChanged("valorGasto");
					this.OnvalorGastoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="cliente_compra", Storage="_compras", ThisKey="idclientes", OtherKey="jogos_idjogos")]
		public EntitySet<compra> compras
		{
			get
			{
				return this._compras;
			}
			set
			{
				this._compras.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_compras(compra entity)
		{
			this.SendPropertyChanging();
			entity.cliente = this;
		}
		
		private void detach_compras(compra entity)
		{
			this.SendPropertyChanging();
			entity.cliente = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.compra")]
	public partial class compra : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idCompra;
		
		private int _jogos_idjogos;
		
		private int _clientes_idclientes;
		
		private System.Nullable<System.DateTime> _dtCompra;
		
		private System.Nullable<int> _quantidade;
		
		private System.Nullable<float> _valor;
		
		private EntityRef<cliente> _cliente;
		
		private EntityRef<jogo> _jogo;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidCompraChanging(int value);
    partial void OnidCompraChanged();
    partial void Onjogos_idjogosChanging(int value);
    partial void Onjogos_idjogosChanged();
    partial void Onclientes_idclientesChanging(int value);
    partial void Onclientes_idclientesChanged();
    partial void OndtCompraChanging(System.Nullable<System.DateTime> value);
    partial void OndtCompraChanged();
    partial void OnquantidadeChanging(System.Nullable<int> value);
    partial void OnquantidadeChanged();
    partial void OnvalorChanging(System.Nullable<float> value);
    partial void OnvalorChanged();
    #endregion
		
		public compra()
		{
			this._cliente = default(EntityRef<cliente>);
			this._jogo = default(EntityRef<jogo>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idCompra", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int idCompra
		{
			get
			{
				return this._idCompra;
			}
			set
			{
				if ((this._idCompra != value))
				{
					this.OnidCompraChanging(value);
					this.SendPropertyChanging();
					this._idCompra = value;
					this.SendPropertyChanged("idCompra");
					this.OnidCompraChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_jogos_idjogos", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int jogos_idjogos
		{
			get
			{
				return this._jogos_idjogos;
			}
			set
			{
				if ((this._jogos_idjogos != value))
				{
					if ((this._cliente.HasLoadedOrAssignedValue || this._jogo.HasLoadedOrAssignedValue))
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onjogos_idjogosChanging(value);
					this.SendPropertyChanging();
					this._jogos_idjogos = value;
					this.SendPropertyChanged("jogos_idjogos");
					this.Onjogos_idjogosChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_clientes_idclientes", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int clientes_idclientes
		{
			get
			{
				return this._clientes_idclientes;
			}
			set
			{
				if ((this._clientes_idclientes != value))
				{
					this.Onclientes_idclientesChanging(value);
					this.SendPropertyChanging();
					this._clientes_idclientes = value;
					this.SendPropertyChanged("clientes_idclientes");
					this.Onclientes_idclientesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dtCompra", DbType="DateTime")]
		public System.Nullable<System.DateTime> dtCompra
		{
			get
			{
				return this._dtCompra;
			}
			set
			{
				if ((this._dtCompra != value))
				{
					this.OndtCompraChanging(value);
					this.SendPropertyChanging();
					this._dtCompra = value;
					this.SendPropertyChanged("dtCompra");
					this.OndtCompraChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_quantidade", DbType="Int")]
		public System.Nullable<int> quantidade
		{
			get
			{
				return this._quantidade;
			}
			set
			{
				if ((this._quantidade != value))
				{
					this.OnquantidadeChanging(value);
					this.SendPropertyChanging();
					this._quantidade = value;
					this.SendPropertyChanged("quantidade");
					this.OnquantidadeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_valor", DbType="Real")]
		public System.Nullable<float> valor
		{
			get
			{
				return this._valor;
			}
			set
			{
				if ((this._valor != value))
				{
					this.OnvalorChanging(value);
					this.SendPropertyChanging();
					this._valor = value;
					this.SendPropertyChanged("valor");
					this.OnvalorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="cliente_compra", Storage="_cliente", ThisKey="jogos_idjogos", OtherKey="idclientes", IsForeignKey=true)]
		public cliente cliente
		{
			get
			{
				return this._cliente.Entity;
			}
			set
			{
				cliente previousValue = this._cliente.Entity;
				if (((previousValue != value) 
							|| (this._cliente.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._cliente.Entity = null;
						previousValue.compras.Remove(this);
					}
					this._cliente.Entity = value;
					if ((value != null))
					{
						value.compras.Add(this);
						this._jogos_idjogos = value.idclientes;
					}
					else
					{
						this._jogos_idjogos = default(int);
					}
					this.SendPropertyChanged("cliente");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="jogo_compra", Storage="_jogo", ThisKey="jogos_idjogos", OtherKey="idjogos", IsForeignKey=true)]
		public jogo jogo
		{
			get
			{
				return this._jogo.Entity;
			}
			set
			{
				jogo previousValue = this._jogo.Entity;
				if (((previousValue != value) 
							|| (this._jogo.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._jogo.Entity = null;
						previousValue.compras.Remove(this);
					}
					this._jogo.Entity = value;
					if ((value != null))
					{
						value.compras.Add(this);
						this._jogos_idjogos = value.idjogos;
					}
					else
					{
						this._jogos_idjogos = default(int);
					}
					this.SendPropertyChanged("jogo");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
